services:
  app:
    build: .
    container_name: vucu_app
    ports:
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9093/"]
      interval: 30s
      timeout: 10s
      retries: 3
